### PR TITLE
Add support for custom root element

### LINKED ISSUE #49: [Feat request] Support different root element
Currently the lib decide about what is the root element to use for the query [see this line](https://github.com/chromaui/storybook-addon-pseudo-states/blob/main/src/withPseudoState.js#L83). 

The issue with this approach, is that sometimes the elements we want to query are rendered outside of this "root" element, E.g: Modals, popovers and portals in general that are attached to the `document.body`.

I don't see any way to work around this issue with the current implementation, so I'm suggesting an additional API that will allow consumers to pass a root element:

For example:

```js
pseudo: {
  root: document.body, // <- new API
  hover: '.my-tooltip'
}
```

This can be done in the [applyParameter function](https://github.com/chromaui/storybook-addon-pseudo-states/blob/main/src/withPseudoState.js#L26), we just need to take in account the `root` parameter and have a fallback to whatever we have today in case the consumer didn't pass it.

```js
  const {root = rootElement, ...parameters} = parameter // <- get the root param with a fallback and also filter it out from the rest of the parameters (i.e states).

  Object.entries(parameters || {}).forEach(_ref => {
    let [state, value] = _ref;

    if (typeof value === "boolean") {
      // default API - applying pseudo class to root element.
      add(root, value && state);
    } else if (typeof value === "string") {
        // explicit selectors API - applying pseudo class to a specific element
        root.querySelectorAll(value).forEach(el => add(el, state));

    } else if (Array.isArray(value)) {
      // explicit selectors API - we have an array (of strings) recursively handle each one
      value.forEach(sel => root.querySelectorAll(sel).forEach(el => add(el, state)));
    }
  });
```

@ghengeveld  WDYT?

### PR DESCRIPTION
**Pull request by sag1v**
Fixes #49

### CODE REVIEW

**Comment by sag1v** [comment]
@ghengeveld / @thafryer  Can you review please?

**Comment by sag1v** [comment]
This PR needs some love 😀 
cc @ghengeveld @thafryer

**Comment by sag1v** [comment]
rebased from latest changes of remote

**Comment by ghengeveld** [comment]
This is awesome. Sorry it took so long to get to it. I've tweaked the types and code a little bit to fix a state synchronization issue, but other than that this is great. Nice work 👍

**Review by ghengeveld — APPROVED** [review]

**Comment by sag1v** [comment]
Thanks @ghengeveld ! 🙏🤓

**Pull request merged**
