### PR TITLE
Add support for targeting specific elements

### LINKED ISSUE #4: [Feature request] Target only specific elements with the hover-state
Hey!

Great plugin, already wrote tons of stories that finally need to have their pseudo states checked :)

One feature idea I had was being able to target just a specific element rather than activating the pseudo-state on all elements.

A good example for this would be a `Select` or a `List`.

```
[ List item 1 ]
[ List item 2 ]
[ List item 3 ]
[ List item 4 ]
```

If I want to check that an element has the correct hover state, I kinda just want to activate it on one item.

I'm not sure how that'd look in an implementation, but I think we might need to be able to get our hands on the `WithPseudoState` and wrap it around specific components, i.e.
```
<WithPseudoState state="hover" target="[data-testid=3]">
  <List
    items={[
      { id: 1, label: 'Item 1' },
      { id: 2, label: 'Item 2' },
      { id: 3, label: 'Item 3' },
      { id: 4, label: 'Item 4' },
    ]}
  />
</WithPseudoState>
```

I've completely made this up but maybe something along those lines could work?

Thanks a lot!

### LINKED ISSUE #5: [Feature Request]: Activate several pseudo states
Hi,

Another feature I think could be hugely beneficial would be being able to activate several pseudo-states. This would be especially useful when having to save the amount of screenshots you take.

The way I could see this working is like this:

```
const Template = (args) => (
  <>
    <h1>Buttons: {args.pseudo}</h1>
    
    <Button>Default Button</Button>
    <ButtonText>Text Button</ButtonText>
    <ButtonOutline>Text Button</ButtonOutline>
   </>
)

Template.args = { pseudo: ['idle', 'hover', 'focus', 'active'] } 
```

Then the plugin could loop over the given states and render it like this:
```
<>
  <Template pseudo="idle" />
  <Template pseudo="hover" />
  <Template pseudo="focus" />
  <Template pseudo="active" />
</> 
```

That would be great because I could save myself the time writing loads of stories activating different states.

Let me know what you think!

### PR DESCRIPTION
**Pull request by sag1v**
resolve #4 and resolve #5

Adds support for specific selector (or array of selectors). 

For example:

```jsx
export const DirectSelector = () => (
  <div>
    <Button>Regular</Button>
    <Button data-id="hover">Hover</Button>
    <Button data-id="focus">Focus</Button>
    <Button data-id="active">Active</Button>
    <div data-id="hover-group">
      <h3>Multiple hovered button grouped</h3>
      <Button>Hovered 1</Button>
      <Button>Hovered 2</Button>
      <Button>Hovered 3</Button>
    </div>
  </div>
)

DirectSelector.parameters = {
  pseudo: {
    useExplicitSelectors: true,
    hover: ['[data-id="hover"]', '[data-id="hover-group"] button'],
    focus: '[data-id="focus"]',
    active: ['[data-id="active"]']
  },
}
```

image

## Warning
~Currently this PR breaks the current API and doesn't support passing booleans (and modifying the root element), meaning consumers must pass a selector.~
I didn't handle/change any code related to shadow DOM, so it might be broken.

This is a WIP so let's discuss 🙂

### CODE REVIEW

**Comment by sag1v** [comment]
cc @ghengeveld

**Comment by sag1v** [comment]
@ghengeveld hi, any estimation on when this will get reviewed?

**Comment by sag1v** [comment]
> Nice work! Really looking forward to making the addon more flexible.
> 
> I have some concerns about web components, so we should do some proper QA before merging.

Thanks 👍
How do you plan on testing web components?

**Comment by ghengeveld** [comment]
> > Nice work! Really looking forward to making the addon more flexible.
> > I have some concerns about web components, so we should do some proper QA before merging.
> 
> Thanks 👍 How do you plan on testing web components?

I typically test web components manually, using the [stories](https://github.com/chromaui/storybook-addon-pseudo-states/tree/main/stories) in the project's Storybook (`CustomElement` and `ShadowRoot`). So if you run the Storybook and verify that those stories look good, then I'm happy 👍

**Comment by sag1v** [comment]
@ghengeveld I've browsed these stories and it looks fine to me.

**Comment by sag1v** [comment]
Hi @ghengeveld m8, what are the next action items to push this PR forward?

**Comment by ghengeveld** [comment]
@sag1v Would be nice to have a little documentation in the README for it.

I'm playing around with it now an running into an issue (toolbar toggles don't seem to work anymore), but once that's resolved and we have docs, I'm happy to merge.

**Comment by ghengeveld** [comment]
Something weird is going on with the toggles when using your branch. I'll have to take a closer look.
Try opening Button > Default and using the state toggles in the toolbar. If you enable one (e.g. `:active`) and then another (e.g. `:hover`), then the first one will no longer be applied and also you won't be able to fix it without reloading.

**Comment by sag1v** [comment]
@ghengeveld  I've checked your last commit, unfortunately it still a mess. I think i have a breakthrough but still have issues with the docs.

I'm not sure why we have this check inside `rewriteStyleSheets` :

```
  for (const sheet of styleSheets) {
    if (sheet._pseudoStatesRewritten) {
      continue
    } else {
      sheet._pseudoStatesRewritten = true
    }
``` 

But removing this check helps solve some of the issues.


I moved some code around and made some changes, its mostly working in canvas (beside 1 issue that the default story "remembers" the previous state untill we play with the toggles). Docs tab on the other hand is broken and i don't know why. 
I'm not committing the changes yet because my change is not complete but i'm pasting it here for reference:

I think we have an issue with the way we handle the storybook events, i'm not an expert with this field and i lack some knowledge regarding the life cycle of these events so i would love to get some help.

withPseudoState.js

```js
/* eslint-env browser */
import { addons, useEffect } from "@storybook/addons"
import {
  DOCS_RENDERED,
  STORY_CHANGED,
  STORY_RENDERED,
  UPDATE_GLOBALS,
} from "@storybook/core-events"

import { PSEUDO_STATES, REWRITE_STYLESHEET } from "./constants"
import { splitSelectors } from "./splitSelectors"
import { useCallback } from "react"

const pseudoStates = Object.values(PSEUDO_STATES)
const matchOne = new RegExp(`:(${pseudoStates.join("|")})`)
const matchAll = new RegExp(`:(${pseudoStates.join("|")})`, "g")

// Drops any existing pseudo state classnames that carried over from a previously viewed story
// before adding the new classnames. We do this the old-fashioned way, for IE compatibility.
const applyClasses = (element, classnames) => {
  element.className = element.className
    .split(" ")
    .filter((classname) => classname && classname.indexOf("pseudo-") !== 0)
    .concat(...classnames)
    .join(" ")
}

const applyParameter = (rootElement, parameter) =>
  Object.entries(parameter || {})
    .reduce((acc, [state, value]) => {
      const set = (target, state) => acc.set(target, new Set([...(acc.get(target) || []), state]))
      if (typeof value === "boolean") {
        // default API - applying pseudo class to root element.
        set(rootElement, value && state)
      } else if (typeof value === "string") {
        // explicit selectors API - applying pseudo class to a specific element
        rootElement.querySelectorAll(value).forEach((el) => set(el, state))
      } else if (Array.isArray(value)) {
        // explicit selectors API - we have an array (of strings) recursively handle each one
        value.forEach((sel) => rootElement.querySelectorAll(sel).forEach((el) => set(el, state)))
      }
      return acc
    }, new Map())
    .forEach((states, target) => {
      const classnames = []
      states.forEach((key) => PSEUDO_STATES[key] && classnames.push(`pseudo-${PSEUDO_STATES[key]}`))
      applyClasses(target, classnames)
    })

// Traverses ancestry to collect relevant pseudo classnames, and applies them to the shadow host.
// Shadow DOM can only access classes on its host. Traversing is needed to mimic the CSS cascade.
const updateShadowHost = (shadowHost) => {
  const classnames = new Set()
  for (let element = shadowHost.parentElement; element; element = element.parentElement) {
    if (!element.className) continue
    element.className
      .split(" ")
      .filter((classname) => classname.indexOf("pseudo-") === 0)
      .forEach((classname) => classnames.add(classname))
  }
  applyClasses(shadowHost, classnames)
}

// Keep track of attached shadow host elements for the current story
const shadowHosts = new Set()
addons.getChannel().on(STORY_CHANGED, () => shadowHosts.clear())

// Global decorator that rewrites stylesheets and applies classnames to render pseudo styles
export const withPseudoState = (StoryFn, { viewMode, parameters, id, globals: globalsArgs }) => {
  const { pseudo: parameter } = parameters
  const { pseudo: globals } = globalsArgs
  const channel = addons.getChannel()
  channel.emit(REWRITE_STYLESHEET)

  const subScriber = useCallback(() => {
    // we combine parameter with globals though it will also work without globals for some reason
    const combinedParams = { ...parameter, ...globals }
    rewriteStyleSheets(null, combinedParams) 
  }, [parameter, globals])
  useEffect(() => {
    const events = [STORY_RENDERED, DOCS_RENDERED, REWRITE_STYLESHEET]

    events.forEach((event) => channel.on(event, subScriber))

    return () => {
      events.forEach((event) => channel.removeListener(event, subScriber))
    }
  }, [subScriber])

  // Sync parameter to globals, used by the toolbar (only in canvas as this
  // doesn't make sense for docs because many stories are displayed at once)
  useEffect(() => {
    if (parameter !== globals && viewMode === "story") {
      channel.emit(UPDATE_GLOBALS, {
        globals: { pseudo: parameter },
      })
    }
  }, [parameter, viewMode])

  // Convert selected states to classnames and apply them to the story root element.
  // Then update each shadow host to redetermine its own pseudo classnames.
  useEffect(() => {
    const timeout = setTimeout(() => {
      const element = document.getElementById(viewMode === "docs" ? `story--${id}` : `root`)
      applyParameter(element, globals)
      shadowHosts.forEach(updateShadowHost)
    }, 0)
    return () => clearTimeout(timeout)
  }, [globals, viewMode])

  return StoryFn()
}

const warnings = new Set()
const warnOnce = (message) => {
  if (warnings.has(message)) return
  // eslint-disable-next-line no-console
  console.warn(message)
  warnings.add(message)
}

// Rewrite CSS rules for pseudo-states on all stylesheets to add an alternative selector
function rewriteStyleSheets(shadowRoot, options = {}) {
  const { useExplicitSelectors } = options
  let styleSheets = shadowRoot ? shadowRoot.styleSheets : document.styleSheets
  if (shadowRoot?.adoptedStyleSheets?.length) styleSheets = shadowRoot.adoptedStyleSheets
  console.log("rewriteStyleSheets", options)
  for (const sheet of styleSheets) {
    if (sheet._pseudoStatesRewritten) {
      //continue
    } else {
      //sheet._pseudoStatesRewritten = true
    }

    try {
      let index = 0
      for (const { cssText, selectorText } of sheet.cssRules) {
        if (matchOne.test(selectorText)) {
          const selectors = splitSelectors(selectorText)
          const newRule = cssText.replace(
            selectorText,
            selectors
              .flatMap((selector) => {
                if (selector.includes(".pseudo-")) return []
                const states = []
                const plainSelector = selector.replace(matchAll, (_, state) => {
                  if (useExplicitSelectors) {
                    return `.pseudo-${state}`
                  }
                  states.push(state)
                  return ""
                })
                let stateSelector
                if (!matchOne.test(selector)) {
                  return [selector]
                }
                if (selector.startsWith(":host(") || selector.startsWith("::slotted(")) {
                  stateSelector = states.reduce(
                    (acc, state) => acc.replaceAll(`:${state}`, `.pseudo-${state}`),
                    selector
                  )
                } else if (shadowRoot) {
                  stateSelector = `:host(${states
                    .map((s) => `.pseudo-${s}`)
                    .join("")}) ${plainSelector}`
                } else {
                  if (useExplicitSelectors) {
                    // Replace the :pseudo selector with .class selector on the element directly, rather than an ancestor element.
                    // For example, instead of rewriting `button:hover` to `.pseudo-hover button`, rewrite it to `button.pseudo-hover`.
                    stateSelector = plainSelector
                  } else {
                    stateSelector = `${states.map((s) => `.pseudo-${s}`).join("")} ${plainSelector}`
                  }
                }
                return [selector, stateSelector]
              })
              .join(", ")
          )
          sheet.deleteRule(index)
          sheet.insertRule(newRule, index)
          if (shadowRoot) shadowHosts.add(shadowRoot.host)
        }
        index++
        if (index > 1000) {
          warnOnce("Reached maximum of 1000 pseudo selectors per sheet, skipping the rest.")
          break
        }
      }
    } catch (e) {
      if (e.toString().includes("cssRules")) {
        warnOnce(`Can't access cssRules, likely due to CORS restrictions: ${sheet.href}`)
      } else {
        // eslint-disable-next-line no-console
        console.error(e, sheet.href)
      }
    }
  }
}

// Reinitialize CSS enhancements every time the story changes
//addons.getChannel().on(STORY_RENDERED, () => rewriteStyleSheets())

// Reinitialize CSS enhancements every time a docs page is rendered
// addons.getChannel().on(DOCS_RENDERED, () => rewriteStyleSheets())

// addons.getChannel().on(REWRITE_STYLESHEET, (...args) => rewriteStyleSheets(null, ...args))

// IE doesn't support shadow DOM
if (Element.prototype.attachShadow) {
  // Monkeypatch the attachShadow method so we can handle pseudo styles inside shadow DOM
  Element.prototype._attachShadow = Element.prototype.attachShadow
  Element.prototype.attachShadow = function attachShadow(init) {
    // Force "open" mode, so we can access the shadowRoot
    const shadowRoot = this._attachShadow({ ...init, mode: "open" })
    // Wait for it to render and apply its styles before rewriting them
    requestAnimationFrame(() => {
      rewriteStyleSheets(shadowRoot)
      updateShadowHost(shadowRoot.host)
    })
    return shadowRoot
  }
}

```

**Comment by ghengeveld** [comment]
@sag1v Fixed it now :)

**Comment by ghengeveld** [comment]
@sag1v Can you check out my latest commit and verify if you think it looks good / works well?

**Comment by sag1v** [comment]
@ghengeveld I'm on it :)

**Comment by ghengeveld** [comment]
I'll write up a README update to add this new string/array config option.

**Comment by sag1v** [comment]
@ghengeveld Canvas works great!

Unfortunately the Docs still broken (same issue i had)
image

image

**Comment by sag1v** [comment]
@ghengeveld 

I think that in `rewriteRule` we are failing to append the correct rule, so we end up with an illegal rule like:

```css
.something:not()
```

instead of

```css
.something:not(:focus-visible)
```

**Review by ghengeveld — APPROVED** [review]

**Comment by ghengeveld** [comment]
@sag1v Do we need anything else or should I merge and release this thing?

**Comment by sag1v** [comment]
@ghengeveld LGTM lets do it! 🥳

**Comment by Codex-** [comment]
I wouldn't have known about `useExplicitSelectors` without stumbling across this PR, it's saved me a tonne of time and pain, would love to see this added to the docs (if it's there then my bad, could not find it at all)

**Pull request merged**
