### PR TITLE
Fix media queries breaking rules override

### LINKED ISSUE #57: Media queries mess up stylesheet override
Because index is not incremented [here](https://github.com/chromaui/storybook-addon-pseudo-states/blob/main/src/rewriteStyleSheet.js#L67) (it gets transpiled to `if (!("selectorText" in cssRule)) continue;`, media queries just go to the next rule. This leads to a situation where
```css
@media only screen and (max-width: 790px) {
    .test {
    	background-color: green;
	}
}

.test {
    background-color: blue;
}

.test:hover {
    background-color: red;
}

.test2:hover {
	background-color: white;
}
```
is rewritten to
```css
@media only screen and (max-width: 790px) {
    .test {
    	background-color: green;
	}
}

.test:hover, .pseudo-hover.test, .pseudo-hover .test {
    background-color: red;
}

.test2:hover, .pseudo-hover.test2, .pseudo-hover .test2 {
	background-color: white;
}

.test2:hover {
	background-color: white;
}
```

I will open a PR fixing soon

### PR DESCRIPTION
**Pull request by filipw01**
Closes #57 

<details>
  <summary>📦 Published PR as canary version: <code>1.15.5--canary.58.b3ff6ae.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install storybook-addon-pseudo-states@1.15.5--canary.58.b3ff6ae.0
  # or 
  yarn add storybook-addon-pseudo-states@1.15.5--canary.58.b3ff6ae.0
  ```
</details>

### CODE REVIEW

**Comment by wladiston** [comment]
This does solve some cases, not all though. Im still having few problems which is hard to track

**Comment by filipw01** [comment]
@wladiston I doubt this is related to the original issue. The issue was that loop was skipped before incrementing index

Can you send the CSS input and output that causes issues for you?

**Comment by wladiston** [comment]
I've created this reproduction here
https://github.com/wladiston/chakra-sb7-bug-repro

Your PR solves this problem but I still have others stories breaking on another SB. Gonna update that repro to see If I can narrow it down

**Comment by wladiston** [comment]
Forget about it. Messed up few stories while migrating to v7. This PR works perfect and should be merged

**Review by JReinhold — APPROVED** [review]
LGTM 💪  thanks for this!

**Pull request merged**
