### PR TITLE
Remove redundant Regex negative lookbehind

### PR DESCRIPTION
**Pull request by filipw01**
Closes: #66

### CODE REVIEW

**Comment by filipw01** [comment]
@valentinpalkovic I see you added this negative lookbehind that I'm removing now. Do you remember why you added it, maybe I'm missing some edge case

@ghengeveld Could you review as well?

**Comment by valentinpalkovic** [comment]
Honestly, I don't remember! :/

**Comment by JReinhold** [comment]
I'm hesitant to merge this until tests have passed. I don't know why CI didn't trigger here. Could you create a non-content commit to hopefully trigger the CI?

**Comment by filipw01** [comment]
All tests are passing locally, but I don't know why the CI doesn't trigger here 😕

**Comment by filipw01** [comment]
@ghengeveld Why was this closed? Is it because next was merged into main? Should I reopen this, but with main branch as base instead of next

**Pull request closed without merging**
